/*
 * Copyright (c) 2024 Nordic Semiconductor ASA
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#if defined(CONFIG_BT_CTLR_NRF_GRTC)
#if !defined(CONFIG_BOARD_EULERBSIM)
#define HAL_CNTR_GRTC_CC_IDX_TICKER 10
#else
#define HAL_CNTR_GRTC_CC_IDX_TICKER 4
#endif
#define HAL_CNTR_GRTC_EVENT_COMPARE_TICKER \
	_CONCAT(NRF_GRTC_EVENT_COMPARE_, HAL_CNTR_GRTC_CC_IDX_TICKER)
#define HAL_CNTR_GRTC_INTENSET_COMPARE_TICKER_Msk \
	_CONCAT(_CONCAT(GRTC_INTENSET1_COMPARE, HAL_CNTR_GRTC_CC_IDX_TICKER), _Msk)
#if !defined(CONFIG_BOARD_EULERBSIM)
#define HAL_CNTR_GRTC_CC_IDX_RADIO  11
#else
#define HAL_CNTR_GRTC_CC_IDX_RADIO  5
#endif
#define HAL_CNTR_GRTC_EVENT_COMPARE_RADIO \
	_CONCAT(NRF_GRTC_EVENT_COMPARE_, HAL_CNTR_GRTC_CC_IDX_RADIO)
#endif /* CONFIG_BT_CTLR_NRF_GRTC */
