#include <gap_appearance.h>

const char * appearance_category_str(enum gap_appearance_category appearance_category)
{
    switch (appearance_category) {
        default: return "Invalid appearance category";
        case GAP_APPEARANCE_CATEGORY_UNKNOWN: return "Unknown";
        case GAP_APPEARANCE_CATEGORY_PHONE: return "Phone";
        case GAP_APPEARANCE_CATEGORY_COMPUTER: return "Computer";
        case GAP_APPEARANCE_CATEGORY_WATCH: return "Watch";
        case GAP_APPEARANCE_CATEGORY_CLOCK: return "Clock";
        case GAP_APPEARANCE_CATEGORY_DISPLAY: return "Display";
        case GAP_APPEARANCE_CATEGORY_REMOTE_CONTROL: return "Remote Control";
        case GAP_APPEARANCE_CATEGORY_EYE­GLASSES: return "Eye­glasses";
        case GAP_APPEARANCE_CATEGORY_TAG: return "Tag";
        case GAP_APPEARANCE_CATEGORY_KEYRING: return "Keyring";
        case GAP_APPEARANCE_CATEGORY_MEDIA_PLAYER: return "Media Player";
        case GAP_APPEARANCE_CATEGORY_BARCODE_SCANNER: return "Barcode Scanner";
        case GAP_APPEARANCE_CATEGORY_THERMOMETER: return "Thermometer";
        case GAP_APPEARANCE_CATEGORY_HEART_RATE_SENSOR: return "Heart Rate Sensor";
        case GAP_APPEARANCE_CATEGORY_BLOOD_PRESSURE: return "Blood Pressure";
        case GAP_APPEARANCE_CATEGORY_HUMAN_INTERFACE_DEVICE: return "Human Interface Device";
        case GAP_APPEARANCE_CATEGORY_GLUCOSE_METER: return "Glucose Meter";
        case GAP_APPEARANCE_CATEGORY_RUNNING_WALKING_SENSOR: return "Running Walking Sensor";
        case GAP_APPEARANCE_CATEGORY_CYCLING: return "Cycling";
        case GAP_APPEARANCE_CATEGORY_CONTROL_DEVICE: return "Control Device";
        case GAP_APPEARANCE_CATEGORY_NETWORK_DEVICE: return "Network Device";
        case GAP_APPEARANCE_CATEGORY_SENSOR: return "Sensor";
        case GAP_APPEARANCE_CATEGORY_LIGHT_FIXTURES: return "Light Fixtures";
        case GAP_APPEARANCE_CATEGORY_FAN: return "Fan";
        case GAP_APPEARANCE_CATEGORY_HVAC: return "HVAC";
        case GAP_APPEARANCE_CATEGORY_AIR_CONDITIONING: return "Air Conditioning";
        case GAP_APPEARANCE_CATEGORY_HUMIDIFIER: return "Humidifier";
        case GAP_APPEARANCE_CATEGORY_HEATING: return "Heating";
        case GAP_APPEARANCE_CATEGORY_ACCESS_CONTROL: return "Access Control";
        case GAP_APPEARANCE_CATEGORY_MOTORIZED_DEVICE: return "Motorized Device";
        case GAP_APPEARANCE_CATEGORY_POWER_DEVICE: return "Power Device";
        case GAP_APPEARANCE_CATEGORY_LIGHT_SOURCE: return "Light Source";
        case GAP_APPEARANCE_CATEGORY_WINDOW_COVERING: return "Window Covering";
        case GAP_APPEARANCE_CATEGORY_AUDIO_SINK: return "Audio Sink";
        case GAP_APPEARANCE_CATEGORY_AUDIO_SOURCE: return "Audio Source";
        case GAP_APPEARANCE_CATEGORY_MOTORIZED_VEHICLE: return "Motorized Vehicle";
        case GAP_APPEARANCE_CATEGORY_DOMESTIC_APPLIANCE: return "Domestic Appliance";
        case GAP_APPEARANCE_CATEGORY_WEARABLE_AUDIO_DEVICE: return "Wearable Audio Device";
        case GAP_APPEARANCE_CATEGORY_AIRCRAFT: return "Aircraft";
        case GAP_APPEARANCE_CATEGORY_AV_EQUIPMENT: return "AV Equipment";
        case GAP_APPEARANCE_CATEGORY_DISPLAY_EQUIPMENT: return "Display Equipment";
        case GAP_APPEARANCE_CATEGORY_HEARING_AID: return "Hearing aid";
        case GAP_APPEARANCE_CATEGORY_GAMING: return "Gaming";
        case GAP_APPEARANCE_CATEGORY_SIGNAGE: return "Signage";
        case GAP_APPEARANCE_CATEGORY_PULSE_OXIMETER: return "Pulse Oximeter";
        case GAP_APPEARANCE_CATEGORY_WEIGHT_SCALE: return "Weight Scale";
        case GAP_APPEARANCE_CATEGORY_PERSONAL_MOBILITY_DEVICE: return "Personal Mobility Device";
        case GAP_APPEARANCE_CATEGORY_CONTINUOUS_GLUCOSE_MONITOR: return "Continuous Glucose Monitor";
        case GAP_APPEARANCE_CATEGORY_INSULIN_PUMP: return "Insulin Pump";
        case GAP_APPEARANCE_CATEGORY_MEDICATION_DELIVERY: return "Medication Delivery";
        case GAP_APPEARANCE_CATEGORY_OUTDOOR_SPORTS_ACTIVITY: return "Outdoor Sports Activity";
    }
}

const char *gap_appearance_value_str(enum gap_appearance_value appearance_value)
{
    switch (appearance_value) {
        default: return "Invalid appearance value";
        case GAP_APPEARANCE_VALUE_GENERIC_UNKNOWN: return "Generic Unknown";
        case GAP_APPEARANCE_VALUE_GENERIC_PHONE: return "Generic Phone";
        case GAP_APPEARANCE_VALUE_GENERIC_COMPUTER: return "Generic Computer";
        case GAP_APPEARANCE_VALUE_DESKTOP_WORKSTATION: return "Desktop Workstation";
        case GAP_APPEARANCE_VALUE_SERVER­CLASS_COMPUTER: return "Server­class Computer";
        case GAP_APPEARANCE_VALUE_LAPTOP: return "Laptop";
        case GAP_APPEARANCE_VALUE_HANDHELD_PC_PDA_CLAMSHELL: return "Handheld PC/PDA (clamshell)";
        case GAP_APPEARANCE_VALUE_PALM­SIZE_PC_PDA: return "Palm­size PC/PDA";
        case GAP_APPEARANCE_VALUE_WEARABLE_COMPUTER_WATCH_SIZE: return "Wearable computer (watch size)";
        case GAP_APPEARANCE_VALUE_TABLET: return "Tablet";
        case GAP_APPEARANCE_VALUE_DOCKING_STATION: return "Docking Station";
        case GAP_APPEARANCE_VALUE_ALL_IN_ONE: return "All in One";
        case GAP_APPEARANCE_VALUE_BLADE_SERVER: return "Blade Server";
        case GAP_APPEARANCE_VALUE_CONVERTIBLE: return "Convertible";
        case GAP_APPEARANCE_VALUE_DETACHABLE: return "Detachable";
        case GAP_APPEARANCE_VALUE_IOT_GATEWAY: return "IoT Gateway";
        case GAP_APPEARANCE_VALUE_MINI_PC: return "Mini PC";
        case GAP_APPEARANCE_VALUE_STICK_PC: return "Stick PC";
        case GAP_APPEARANCE_VALUE_GENERIC_WATCH: return "Generic Watch";
        case GAP_APPEARANCE_VALUE_SPORTS_WATCH: return "Sports Watch";
        case GAP_APPEARANCE_VALUE_SMARTWATCH: return "Smartwatch";
        case GAP_APPEARANCE_VALUE_GENERIC_CLOCK: return "Generic Clock";
        case GAP_APPEARANCE_VALUE_GENERIC_DISPLAY: return "Generic Display";
        case GAP_APPEARANCE_VALUE_GENERIC_REMOTE_CONTROL: return "Generic Remote Control";
        case GAP_APPEARANCE_VALUE_GENERIC_EYE­GLASSES: return "Generic Eye­glasses";
        case GAP_APPEARANCE_VALUE_GENERIC_TAG: return "Generic Tag";
        case GAP_APPEARANCE_VALUE_GENERIC_KEYRING: return "Generic Keyring";
        case GAP_APPEARANCE_VALUE_GENERIC_MEDIA_PLAYER: return "Generic Media Player";
        case GAP_APPEARANCE_VALUE_GENERIC_BARCODE_SCANNER: return "Generic Barcode Scanner";
        case GAP_APPEARANCE_VALUE_GENERIC_THERMOMETER: return "Generic Thermometer";
        case GAP_APPEARANCE_VALUE_EAR_THERMOMETER: return "Ear Thermometer";
        case GAP_APPEARANCE_VALUE_GENERIC_HEART_RATE_SENSOR: return "Generic Heart Rate Sensor";
        case GAP_APPEARANCE_VALUE_HEART_RATE_BELT: return "Heart Rate Belt";
        case GAP_APPEARANCE_VALUE_GENERIC_BLOOD_PRESSURE: return "Generic Blood Pressure";
        case GAP_APPEARANCE_VALUE_ARM_BLOOD_PRESSURE: return "Arm Blood Pressure";
        case GAP_APPEARANCE_VALUE_WRIST_BLOOD_PRESSURE: return "Wrist Blood Pressure";
        case GAP_APPEARANCE_VALUE_GENERIC_HUMAN_INTERFACE_DEVICE: return "Generic Human Interface Device";
        case GAP_APPEARANCE_VALUE_KEYBOARD: return "Keyboard";
        case GAP_APPEARANCE_VALUE_MOUSE: return "Mouse";
        case GAP_APPEARANCE_VALUE_JOYSTICK: return "Joystick";
        case GAP_APPEARANCE_VALUE_GAMEPAD: return "Gamepad";
        case GAP_APPEARANCE_VALUE_DIGITIZER_TABLET: return "Digitizer Tablet";
        case GAP_APPEARANCE_VALUE_CARD_READER: return "Card Reader";
        case GAP_APPEARANCE_VALUE_DIGITAL_PEN: return "Digital Pen";
        case GAP_APPEARANCE_VALUE_BARCODE_SCANNER: return "Barcode Scanner";
        case GAP_APPEARANCE_VALUE_GENERIC_GLUCOSE_METER: return "Generic Glucose Meter";
        case GAP_APPEARANCE_VALUE_GENERIC_RUNNING_WALKING_SENSOR: return "Generic Running Walking Sensor";
        case GAP_APPEARANCE_VALUE_IN­SHOE_RUNNING_WALKING_SENSOR: return "In­Shoe Running Walking Sensor";
        case GAP_APPEARANCE_VALUE_ON­SHOE_RUNNING_WALKING_SENSOR: return "On­Shoe Running Walking Sensor";
        case GAP_APPEARANCE_VALUE_ON­HIP_RUNNING_WALKING_SENSOR: return "On­Hip Running Walking Sensor";
        case GAP_APPEARANCE_VALUE_GENERIC_CYCLING: return "Generic Cycling";
        case GAP_APPEARANCE_VALUE_CYCLING_COMPUTER: return "Cycling Computer";
        case GAP_APPEARANCE_VALUE_SPEED_SENSOR: return "Speed Sensor";
        case GAP_APPEARANCE_VALUE_CADENCE_SENSOR: return "Cadence Sensor";
        case GAP_APPEARANCE_VALUE_POWER_SENSOR: return "Power Sensor";
        case GAP_APPEARANCE_VALUE_SPEED_AND_CADENCE_SENSOR: return "Speed and Cadence Sensor";
        case GAP_APPEARANCE_VALUE_GENERIC_CONTROL_DEVICE: return "Generic Control Device";
        case GAP_APPEARANCE_VALUE_SWITCH: return "Switch";
        case GAP_APPEARANCE_VALUE_MULTI­SWITCH: return "Multi­switch";
        case GAP_APPEARANCE_VALUE_BUTTON: return "Button";
        case GAP_APPEARANCE_VALUE_SLIDER: return "Slider";
        case GAP_APPEARANCE_VALUE_ROTARY_SWITCH: return "Rotary Switch";
        case GAP_APPEARANCE_VALUE_TOUCH_PANEL: return "Touch Panel";
        case GAP_APPEARANCE_VALUE_SINGLE_SWITCH: return "Single Switch";
        case GAP_APPEARANCE_VALUE_DOUBLE_SWITCH: return "Double Switch";
        case GAP_APPEARANCE_VALUE_TRIPLE_SWITCH: return "Triple Switch";
        case GAP_APPEARANCE_VALUE_BATTERY_SWITCH: return "Battery Switch";
        case GAP_APPEARANCE_VALUE_ENERGY_HARVESTING_SWITCH: return "Energy Harvesting Switch";
        case GAP_APPEARANCE_VALUE_PUSH_BUTTON: return "Push Button";
        case GAP_APPEARANCE_VALUE_GENERIC_NETWORK_DEVICE: return "Generic Network Device";
        case GAP_APPEARANCE_VALUE_ACCESS_POINT: return "Access Point";
        case GAP_APPEARANCE_VALUE_MESH_DEVICE: return "Mesh Device";
        case GAP_APPEARANCE_VALUE_MESH_NETWORK_PROXY: return "Mesh Network Proxy";
        case GAP_APPEARANCE_VALUE_GENERIC_SENSOR: return "Generic Sensor";
        case GAP_APPEARANCE_VALUE_MOTION_SENSOR: return "Motion Sensor";
        case GAP_APPEARANCE_VALUE_AIR_QUALITY_SENSOR: return "Air quality Sensor";
        case GAP_APPEARANCE_VALUE_TEMPERATURE_SENSOR: return "Temperature Sensor";
        case GAP_APPEARANCE_VALUE_HUMIDITY_SENSOR: return "Humidity Sensor";
        case GAP_APPEARANCE_VALUE_LEAK_SENSOR: return "Leak Sensor";
        case GAP_APPEARANCE_VALUE_SMOKE_SENSOR: return "Smoke Sensor";
        case GAP_APPEARANCE_VALUE_OCCUPANCY_SENSOR: return "Occupancy Sensor";
        case GAP_APPEARANCE_VALUE_CONTACT_SENSOR: return "Contact Sensor";
        case GAP_APPEARANCE_VALUE_CARBON_MONOXIDE_SENSOR: return "Carbon Monoxide Sensor";
        case GAP_APPEARANCE_VALUE_CARBON_DIOXIDE_SENSOR: return "Carbon Dioxide Sensor";
        case GAP_APPEARANCE_VALUE_AMBIENT_LIGHT_SENSOR: return "Ambient Light Sensor";
        case GAP_APPEARANCE_VALUE_ENERGY_SENSOR: return "Energy Sensor";
        case GAP_APPEARANCE_VALUE_COLOR_LIGHT_SENSOR: return "Color Light Sensor";
        case GAP_APPEARANCE_VALUE_RAIN_SENSOR: return "Rain Sensor";
        case GAP_APPEARANCE_VALUE_FIRE_SENSOR: return "Fire Sensor";
        case GAP_APPEARANCE_VALUE_WIND_SENSOR: return "Wind Sensor";
        case GAP_APPEARANCE_VALUE_PROXIMITY_SENSOR: return "Proximity Sensor";
        case GAP_APPEARANCE_VALUE_MULTI­SENSOR: return "Multi­Sensor";
        case GAP_APPEARANCE_VALUE_FLUSH_MOUNTED_SENSOR: return "Flush mounted sensor";
        case GAP_APPEARANCE_VALUE_CEILING_MOUNTED_SENSOR: return "Ceiling mounted sensor";
        case GAP_APPEARANCE_VALUE_WALL_MOUNTED_SENSOR: return "Wall mounted sensor";
        case GAP_APPEARANCE_VALUE_MULTISENSOR: return "Multisensor";
        case GAP_APPEARANCE_VALUE_ENERGY_METER: return "Energy Meter";
        case GAP_APPEARANCE_VALUE_FLAME_DETECTOR: return "Flame Detector";
        case GAP_APPEARANCE_VALUE_VEHICLE_TIRE_PRESSURE_SENSOR: return "Vehicle Tire Pressure Sensor";
        case GAP_APPEARANCE_VALUE_GENERIC_LIGHT_FIXTURES: return "Generic Light Fixtures";
        case GAP_APPEARANCE_VALUE_WALL_LIGHT: return "Wall Light";
        case GAP_APPEARANCE_VALUE_CEILING_LIGHT: return "Ceiling Light";
        case GAP_APPEARANCE_VALUE_FLOOR_LIGHT: return "Floor Light";
        case GAP_APPEARANCE_VALUE_CABINET_LIGHT: return "Cabinet Light";
        case GAP_APPEARANCE_VALUE_DESK_LIGHT: return "Desk Light";
        case GAP_APPEARANCE_VALUE_TROFFER_LIGHT: return "Troffer Light";
        case GAP_APPEARANCE_VALUE_PENDANT_LIGHT: return "Pendant Light";
        case GAP_APPEARANCE_VALUE_IN­GROUND_LIGHT: return "In­ground Light";
        case GAP_APPEARANCE_VALUE_FLOOD_LIGHT: return "Flood Light";
        case GAP_APPEARANCE_VALUE_UNDERWATER_LIGHT: return "Underwater Light";
        case GAP_APPEARANCE_VALUE_BOLLARD_WITH_LIGHT: return "Bollard with Light";
        case GAP_APPEARANCE_VALUE_PATHWAY_LIGHT: return "Pathway Light";
        case GAP_APPEARANCE_VALUE_GARDEN_LIGHT: return "Garden Light";
        case GAP_APPEARANCE_VALUE_POLE­TOP_LIGHT: return "Pole­top Light";
        case GAP_APPEARANCE_VALUE_SPOTLIGHT: return "Spotlight";
        case GAP_APPEARANCE_VALUE_LINEAR_LIGHT: return "Linear Light";
        case GAP_APPEARANCE_VALUE_STREET_LIGHT: return "Street Light";
        case GAP_APPEARANCE_VALUE_SHELVES_LIGHT: return "Shelves Light";
        case GAP_APPEARANCE_VALUE_BAY_LIGHT: return "Bay Light";
        case GAP_APPEARANCE_VALUE_EMERGENCY_EXIT_LIGHT: return "Emergency Exit Light";
        case GAP_APPEARANCE_VALUE_LIGHT_CONTROLLER: return "Light controller";
        case GAP_APPEARANCE_VALUE_LIGHT_DRIVER: return "Light driver";
        case GAP_APPEARANCE_VALUE_BULB: return "Bulb";
        case GAP_APPEARANCE_VALUE_LOW­BAY_LIGHT: return "Low­bay Light";
        case GAP_APPEARANCE_VALUE_HIGH­BAY_LIGHT: return "High­bay Light";
        case GAP_APPEARANCE_VALUE_GENERIC_FAN: return "Generic Fan";
        case GAP_APPEARANCE_VALUE_CEILING_FAN: return "Ceiling Fan";
        case GAP_APPEARANCE_VALUE_AXIAL_FAN: return "Axial Fan";
        case GAP_APPEARANCE_VALUE_EXHAUST_FAN: return "Exhaust Fan";
        case GAP_APPEARANCE_VALUE_PEDESTAL_FAN: return "Pedestal Fan";
        case GAP_APPEARANCE_VALUE_DESK_FAN: return "Desk Fan";
        case GAP_APPEARANCE_VALUE_WALL_FAN: return "Wall Fan";
        case GAP_APPEARANCE_VALUE_GENERIC_HVAC: return "Generic HVAC";
        case GAP_APPEARANCE_VALUE_THERMOSTAT: return "Thermostat";
        case GAP_APPEARANCE_VALUE_HUMIDIFIER: return "Humidifier";
        case GAP_APPEARANCE_VALUE_DE­HUMIDIFIER: return "De­humidifier";
        case GAP_APPEARANCE_VALUE_HEATER: return "Heater";
        case GAP_APPEARANCE_VALUE_RADIATOR: return "Radiator";
        case GAP_APPEARANCE_VALUE_BOILER: return "Boiler";
        case GAP_APPEARANCE_VALUE_HEAT_PUMP: return "Heat pump";
        case GAP_APPEARANCE_VALUE_INFRARED_HEATER: return "Infrared heater";
        case GAP_APPEARANCE_VALUE_RADIANT_PANEL_HEATER: return "Radiant panel heater";
        case GAP_APPEARANCE_VALUE_FAN_HEATER: return "Fan heater";
        case GAP_APPEARANCE_VALUE_AIR_CURTAIN: return "Air curtain";
        case GAP_APPEARANCE_VALUE_GENERIC_AIR_CONDITIONING: return "Generic Air Conditioning";
        case GAP_APPEARANCE_VALUE_GENERIC_HUMIDIFIER: return "Generic Humidifier";
        case GAP_APPEARANCE_VALUE_GENERIC_HEATING: return "Generic Heating";
        case GAP_APPEARANCE_VALUE_RADIATOR: return "Radiator";
        case GAP_APPEARANCE_VALUE_BOILER: return "Boiler";
        case GAP_APPEARANCE_VALUE_HEAT_PUMP: return "Heat Pump";
        case GAP_APPEARANCE_VALUE_INFRARED_HEATER: return "Infrared Heater";
        case GAP_APPEARANCE_VALUE_RADIANT_PANEL_HEATER: return "Radiant Panel Heater";
        case GAP_APPEARANCE_VALUE_FAN_HEATER: return "Fan Heater";
        case GAP_APPEARANCE_VALUE_AIR_CURTAIN: return "Air Curtain";
        case GAP_APPEARANCE_VALUE_GENERIC_ACCESS_CONTROL: return "Generic Access Control";
        case GAP_APPEARANCE_VALUE_ACCESS_DOOR: return "Access Door";
        case GAP_APPEARANCE_VALUE_GARAGE_DOOR: return "Garage Door";
        case GAP_APPEARANCE_VALUE_EMERGENCY_EXIT_DOOR: return "Emergency Exit Door";
        case GAP_APPEARANCE_VALUE_ACCESS_LOCK: return "Access Lock";
        case GAP_APPEARANCE_VALUE_ELEVATOR: return "Elevator";
        case GAP_APPEARANCE_VALUE_WINDOW: return "Window";
        case GAP_APPEARANCE_VALUE_ENTRANCE_GATE: return "Entrance Gate";
        case GAP_APPEARANCE_VALUE_DOOR_LOCK: return "Door Lock";
        case GAP_APPEARANCE_VALUE_LOCKER: return "Locker";
        case GAP_APPEARANCE_VALUE_GENERIC_MOTORIZED_DEVICE: return "Generic Motorized Device";
        case GAP_APPEARANCE_VALUE_MOTORIZED_GATE: return "Motorized Gate";
        case GAP_APPEARANCE_VALUE_AWNING: return "Awning";
        case GAP_APPEARANCE_VALUE_BLINDS_OR_SHADES: return "Blinds or Shades";
        case GAP_APPEARANCE_VALUE_CURTAINS: return "Curtains";
        case GAP_APPEARANCE_VALUE_SCREEN: return "Screen";
        case GAP_APPEARANCE_VALUE_GENERIC_POWER_DEVICE: return "Generic Power Device";
        case GAP_APPEARANCE_VALUE_POWER_OUTLET: return "Power Outlet";
        case GAP_APPEARANCE_VALUE_POWER_STRIP: return "Power Strip";
        case GAP_APPEARANCE_VALUE_PLUG: return "Plug";
        case GAP_APPEARANCE_VALUE_POWER_SUPPLY: return "Power Supply";
        case GAP_APPEARANCE_VALUE_LED_DRIVER: return "LED Driver";
        case GAP_APPEARANCE_VALUE_FLUORESCENT_LAMP_GEAR: return "Fluorescent Lamp Gear";
        case GAP_APPEARANCE_VALUE_HID_LAMP_GEAR: return "HID Lamp Gear";
        case GAP_APPEARANCE_VALUE_CHARGE_CASE: return "Charge Case";
        case GAP_APPEARANCE_VALUE_POWER_BANK: return "Power Bank";
        case GAP_APPEARANCE_VALUE_GENERIC_LIGHT_SOURCE: return "Generic Light Source";
        case GAP_APPEARANCE_VALUE_INCANDESCENT_LIGHT_BULB: return "Incandescent Light Bulb";
        case GAP_APPEARANCE_VALUE_LED_LAMP: return "LED Lamp";
        case GAP_APPEARANCE_VALUE_HID_LAMP: return "HID Lamp";
        case GAP_APPEARANCE_VALUE_FLUORESCENT_LAMP: return "Fluorescent Lamp";
        case GAP_APPEARANCE_VALUE_LED_ARRAY: return "LED Array";
        case GAP_APPEARANCE_VALUE_MULTI­COLOR_LED_ARRAY: return "Multi­Color LED Array";
        case GAP_APPEARANCE_VALUE_GENERIC_WINDOW_COVERING: return "Generic Window Covering";
        case GAP_APPEARANCE_VALUE_WINDOW_SHADES: return "Window Shades";
        case GAP_APPEARANCE_VALUE_WINDOW_BLINDS: return "Window Blinds";
        case GAP_APPEARANCE_VALUE_WINDOW_AWNING: return "Window Awning";
        case GAP_APPEARANCE_VALUE_WINDOW_CURTAIN: return "Window Curtain";
        case GAP_APPEARANCE_VALUE_EXTERIOR_SHUTTER: return "Exterior Shutter";
        case GAP_APPEARANCE_VALUE_EXTERIOR_SCREEN: return "Exterior Screen";
        case GAP_APPEARANCE_VALUE_GENERIC_AUDIO_SINK: return "Generic Audio Sink";
        case GAP_APPEARANCE_VALUE_STANDALONE_SPEAKER: return "Standalone Speaker";
        case GAP_APPEARANCE_VALUE_SOUNDBAR: return "Soundbar";
        case GAP_APPEARANCE_VALUE_BOOKSHELF_SPEAKER: return "Bookshelf Speaker";
        case GAP_APPEARANCE_VALUE_STANDMOUNTED_SPEAKER: return "Standmounted Speaker";
        case GAP_APPEARANCE_VALUE_SPEAKERPHONE: return "Speakerphone";
        case GAP_APPEARANCE_VALUE_GENERIC_AUDIO_SOURCE: return "Generic Audio Source";
        case GAP_APPEARANCE_VALUE_MICROPHONE: return "Microphone";
        case GAP_APPEARANCE_VALUE_ALARM: return "Alarm";
        case GAP_APPEARANCE_VALUE_BELL: return "Bell";
        case GAP_APPEARANCE_VALUE_HORN: return "Horn";
        case GAP_APPEARANCE_VALUE_BROADCASTING_DEVICE: return "Broadcasting Device";
        case GAP_APPEARANCE_VALUE_SERVICE_DESK: return "Service Desk";
        case GAP_APPEARANCE_VALUE_KIOSK: return "Kiosk";
        case GAP_APPEARANCE_VALUE_BROADCASTING_ROOM: return "Broadcasting Room";
        case GAP_APPEARANCE_VALUE_AUDITORIUM: return "Auditorium";
        case GAP_APPEARANCE_VALUE_GENERIC_MOTORIZED_VEHICLE: return "Generic Motorized Vehicle";
        case GAP_APPEARANCE_VALUE_CAR: return "Car";
        case GAP_APPEARANCE_VALUE_LARGE_GOODS_VEHICLE: return "Large Goods Vehicle";
        case GAP_APPEARANCE_VALUE_TWO_­WHEELED_VEHICLE: return "2­Wheeled Vehicle";
        case GAP_APPEARANCE_VALUE_MOTORBIKE: return "Motorbike";
        case GAP_APPEARANCE_VALUE_SCOOTER: return "Scooter";
        case GAP_APPEARANCE_VALUE_MOPED: return "Moped";
        case GAP_APPEARANCE_VALUE_THREE_­WHEELED_VEHICLE: return "3­Wheeled Vehicle";
        case GAP_APPEARANCE_VALUE_LIGHT_VEHICLE: return "Light Vehicle";
        case GAP_APPEARANCE_VALUE_QUAD_BIKE: return "Quad Bike";
        case GAP_APPEARANCE_VALUE_MINIBUS: return "Minibus";
        case GAP_APPEARANCE_VALUE_BUS: return "Bus";
        case GAP_APPEARANCE_VALUE_TROLLEY: return "Trolley";
        case GAP_APPEARANCE_VALUE_AGRICULTURAL_VEHICLE: return "Agricultural Vehicle";
        case GAP_APPEARANCE_VALUE_CAMPER___CARAVAN: return "Camper / Caravan";
        case GAP_APPEARANCE_VALUE_RECREATIONAL_VEHICLE___MOTOR_HOME: return "Recreational Vehicle / Motor Home";
        case GAP_APPEARANCE_VALUE_GENERIC_DOMESTIC_APPLIANCE: return "Generic Domestic Appliance";
        case GAP_APPEARANCE_VALUE_REFRIGERATOR: return "Refrigerator";
        case GAP_APPEARANCE_VALUE_FREEZER: return "Freezer";
        case GAP_APPEARANCE_VALUE_OVEN: return "Oven";
        case GAP_APPEARANCE_VALUE_MICROWAVE: return "Microwave";
        case GAP_APPEARANCE_VALUE_TOASTER: return "Toaster";
        case GAP_APPEARANCE_VALUE_WASHING_MACHINE: return "Washing Machine";
        case GAP_APPEARANCE_VALUE_DRYER: return "Dryer";
        case GAP_APPEARANCE_VALUE_COFFEE_MAKER: return "Coffee maker";
        case GAP_APPEARANCE_VALUE_CLOTHES_IRON: return "Clothes iron";
        case GAP_APPEARANCE_VALUE_CURLING_IRON: return "Curling iron";
        case GAP_APPEARANCE_VALUE_HAIR_DRYER: return "Hair dryer";
        case GAP_APPEARANCE_VALUE_VACUUM_CLEANER: return "Vacuum cleaner";
        case GAP_APPEARANCE_VALUE_ROBOTIC_VACUUM_CLEANER: return "Robotic vacuum cleaner";
        case GAP_APPEARANCE_VALUE_RICE_COOKER: return "Rice cooker";
        case GAP_APPEARANCE_VALUE_CLOTHES_STEAMER: return "Clothes steamer";
        case GAP_APPEARANCE_VALUE_GENERIC_WEARABLE_AUDIO_DEVICE: return "Generic Wearable Audio Device";
        case GAP_APPEARANCE_VALUE_EARBUD: return "Earbud";
        case GAP_APPEARANCE_VALUE_HEADSET: return "Headset";
        case GAP_APPEARANCE_VALUE_HEADPHONES: return "Headphones";
        case GAP_APPEARANCE_VALUE_NECK_BAND: return "Neck Band";
        case GAP_APPEARANCE_VALUE_GENERIC_AIRCRAFT: return "Generic Aircraft";
        case GAP_APPEARANCE_VALUE_LIGHT_AIRCRAFT: return "Light Aircraft";
        case GAP_APPEARANCE_VALUE_MICROLIGHT: return "Microlight";
        case GAP_APPEARANCE_VALUE_PARAGLIDER: return "Paraglider";
        case GAP_APPEARANCE_VALUE_LARGE_PASSENGER_AIRCRAFT: return "Large Passenger Aircraft";
        case GAP_APPEARANCE_VALUE_GENERIC_AV_EQUIPMENT: return "Generic AV Equipment";
        case GAP_APPEARANCE_VALUE_AMPLIFIER: return "Amplifier";
        case GAP_APPEARANCE_VALUE_RECEIVER: return "Receiver";
        case GAP_APPEARANCE_VALUE_RADIO: return "Radio";
        case GAP_APPEARANCE_VALUE_TUNER: return "Tuner";
        case GAP_APPEARANCE_VALUE_TURNTABLE: return "Turntable";
        case GAP_APPEARANCE_VALUE_CD_PLAYER: return "CD Player";
        case GAP_APPEARANCE_VALUE_DVD_PLAYER: return "DVD Player";
        case GAP_APPEARANCE_VALUE_BLURAY_PLAYER: return "Bluray Player";
        case GAP_APPEARANCE_VALUE_OPTICAL_DISC_PLAYER: return "Optical Disc Player";
        case GAP_APPEARANCE_VALUE_SET­TOP_BOX: return "Set­Top Box";
        case GAP_APPEARANCE_VALUE_GENERIC_DISPLAY_EQUIPMENT: return "Generic Display Equipment";
        case GAP_APPEARANCE_VALUE_TELEVISION: return "Television";
        case GAP_APPEARANCE_VALUE_MONITOR: return "Monitor";
        case GAP_APPEARANCE_VALUE_PROJECTOR: return "Projector";
        case GAP_APPEARANCE_VALUE_GENERIC_HEARING_AID: return "Generic Hearing aid";
        case GAP_APPEARANCE_VALUE_IN­EAR_HEARING_AID: return "In­ear hearing aid";
        case GAP_APPEARANCE_VALUE_BEHIND­EAR_HEARING_AID: return "Behind­ear hearing aid";
        case GAP_APPEARANCE_VALUE_COCHLEAR_IMPLANT: return "Cochlear Implant";
        case GAP_APPEARANCE_VALUE_GENERIC_GAMING: return "Generic Gaming";
        case GAP_APPEARANCE_VALUE_HOME_VIDEO_GAME_CONSOLE: return "Home Video Game Console";
        case GAP_APPEARANCE_VALUE_PORTABLE_HANDHELD_CONSOLE: return "Portable handheld console";
        case GAP_APPEARANCE_VALUE_GENERIC_SIGNAGE: return "Generic Signage";
        case GAP_APPEARANCE_VALUE_DIGITAL_SIGNAGE: return "Digital Signage";
        case GAP_APPEARANCE_VALUE_ELECTRONIC_LABEL: return "Electronic Label";
        case GAP_APPEARANCE_VALUE_GENERIC_PULSE_OXIMETER: return "Generic Pulse Oximeter";
        case GAP_APPEARANCE_VALUE_FINGERTIP_PULSE_OXIMETER: return "Fingertip Pulse Oximeter";
        case GAP_APPEARANCE_VALUE_WRIST_WORN_PULSE_OXIMETER: return "Wrist Worn Pulse Oximeter";
        case GAP_APPEARANCE_VALUE_GENERIC_WEIGHT_SCALE: return "Generic Weight Scale";
        case GAP_APPEARANCE_VALUE_GENERIC_PERSONAL_MOBILITY_DEVICE: return "Generic Personal Mobility Device";
        case GAP_APPEARANCE_VALUE_POWERED_WHEELCHAIR: return "Powered Wheelchair";
        case GAP_APPEARANCE_VALUE_MOBILITY_SCOOTER: return "Mobility Scooter";
        case GAP_APPEARANCE_VALUE_GENERIC_CONTINUOUS_GLUCOSE_MONITOR: return "Generic Continuous Glucose Monitor";
        case GAP_APPEARANCE_VALUE_GENERIC_INSULIN_PUMP: return "Generic Insulin Pump";
        case GAP_APPEARANCE_VALUE_INSULIN_PUMP_DURABLE_PUMP: return "Insulin Pump, durable pump";
        case GAP_APPEARANCE_VALUE_INSULIN_PUMP_PATCH_PUMP: return "Insulin Pump, patch pump";
        case GAP_APPEARANCE_VALUE_INSULIN_PEN: return "Insulin Pen";
        case GAP_APPEARANCE_VALUE_GENERIC_MEDICATION_DELIVERY: return "Generic Medication Delivery";
        case GAP_APPEARANCE_VALUE_GENERIC_OUTDOOR_SPORTS_ACTIVITY: return "Generic Outdoor Sports Activity";
        case GAP_APPEARANCE_VALUE_LOCATION_DISPLAY: return "Location Display";
        case GAP_APPEARANCE_VALUE_LOCATION_AND_NAVIGATION_DISPLAY: return "Location and Navigation Display";
        case GAP_APPEARANCE_VALUE_LOCATION_POD: return "Location Pod";
        case GAP_APPEARANCE_VALUE_LOCATION_AND_NAVIGATION_POD: return "Location and Navigation Pod";
    }
};
